# Generated by Django 5.2.2 on 2025-06-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(help_text='Unique identifier for product.', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='name of the product.', max_length=255)),
                ('category', models.CharField(help_text='Category of the product.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=10)),
                ('stock_quantity', models.IntegerField(default=0, help_text='current available stock quantity')),
                ('image_url', models.URLField(blank=True, help_text='URL to the product image.', max_length=500, null=True)),
                ('brand', models.CharField(blank=True, help_text='Brand of the product', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the product was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the product was last updated')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
